version: '3.1'
services:
  stats-server:
    build: ./stats
    restart: on-failure
    container_name: stats-server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - stats-db
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=root
        - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
        - SERVER_PORT=9090

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
        - "5433:5432"
    environment:
        - POSTGRES_DB=stats
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root

#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine
