version: '3.1'
services:
  stats-server:
    build: ./stats
    restart: on-failure
    container_name: stats-server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - stats-db
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=root
        - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
        - SERVER_PORT=9090

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
        - "5433:5432"
    environment:
        - POSTGRES_DB=stats
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root

  main-service:
    build: ./service
    restart: on-failure
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5454/main
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SERVER_PORT=8080

  db:
    image: postgres:16.1
    container_name: db
    ports:
      - "6543:5454"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    command:
      - "postgres"
      - "-c"
      - "port=5454"
